### ISSUE TITLE
Role produces leftovers

### ISSUE THREAD

**Issue by walterdolce** [debops/ansible-logrotate#4]
Hi, thank you for implementing this role and opening it up to the community.

I noticed that it produces leftovers though.

Assuming you initially have something like the following:
```
logrotate__config:
  - filename: 'diamond.log'
    log: '/var/log/diamond/diamond.log'
    state: 'present'
    options: |
      compress gzip
      daily
      missingok
      nomail
      noolddir
      notifempty
      rotate 10
      size 50M
```

But then you realise you mistakenly added a "`.log`" in the configuration filename, and so you correct it to the following:
```
logrotate__config:
  - filename: 'diamond'
    log: '/var/log/diamond/diamond.log'
    state: 'present'
    options: |
      compress gzip
      daily
      missingok
      nomail
      noolddir
      notifempty
      rotate 10
      size 50M
```

The `diamond` configuration will be placed correctly in `/etc/logrotate.d` but the erroneous `diamond.log` file will _also_ be there. Whereby nothing but the expected should be placed in that folder.

Unless I am looking at it the wrong way of course..

Thank you.

**Comment by drybjed** [comment]
The role is designed to manage only the files that it knows about. When you first create a `diamond.log` file and then change the configuration to `diamond`, role doesn't know anything about `diamong.log` so it leaves it be.

If you want to remove the mistake, you should add a second entry for it with the correct state. Your second example should look like:
```yaml
logrotate__config:

  - filename: 'diamond.log'
    state: 'absent'

  - filename: 'diamond'
    log: '/var/log/diamond/diamond.log'
    state: 'present'
    options: |
      compress gzip
      daily
      missingok
      nomail
      noolddir
      notifempty
      rotate 10
```
This way role will know about the second file and what to do with it.
